### ISSUE TITLE
nil is not a symbol

### ISSUE THREAD

**Issue by douglasjarquin** [texel/buildmeister#1]
In trying to setup buildmeister I get the following error message:

```
Quitting Buildmeister due to error: nil is not a symbol`
/Library/Ruby/Gems/1.8/gems/texel-buildmeister-0.8.1/bin/buildmeister:6:in `send'
/Library/Ruby/Gems/1.8/gems/texel-buildmeister-0.8.1/bin/buildmeister:6
/usr/bin/buildmeister:19:in `load'
/usr/bin/buildmeister:19
```

Note, the `.buildmeister_config.yml` file is different in the gem source, than it is in the git repo. I am using the file located at `/Library/Ruby/Gems/1.8/gems/texel-buildmeister-0.8.1/config/buildmeister_config.sample.yml`, which seems to be more recent.

**Comment by texel** [comment]
It looks like your'e using an outdated version - the latest is on Gemcutter, and it's not prefixed with "texel-". I'll check and make sure the buildmeister_config.sample.yml is up to date. Thanks for bringing this to my attention!

**Comment by douglasjarquin** [comment]
Thanks for setting me straight. For reference, get this gem here from now: http://rubygems.org/gems/buildmeister.

**Comment by texel** [comment]
So it's working for you now?

**Comment by douglasjarquin** [comment]
After weeding through some config file mistakes, I am still getting the "nil is not a symbol" error:

```
Quitting Buildmeister due to error: nil is not a symbol
/Library/Ruby/Gems/1.8/gems/buildmeister-1.0.7/bin/buildmeister:10:in `send'
/Library/Ruby/Gems/1.8/gems/buildmeister-1.0.7/bin/buildmeister:10
/usr/bin/buildmeister:19:in `load'
/usr/bin/buildmeister:19
```

I am going to triple check my environment, and then try to track the error down a bit more, but if you have any ideas I would greatly appreciate your help.

**Comment by texel** [comment]
Ok... well first off, what command are you typing? It might behave differently depending on whether you're doing a notify, move_all, etc. Second, could you post a redacted version of your buildmeister_config.yml? Third, did it work first and then stop working, or has it never worked?

**Comment by douglasjarquin** [comment]
Oh boy, do I feel stupid. I was running the `buildmeister` command without any parameters, assuming that it would not return any output if it was setup correctly. Ran `buildmeister notify` and sure enough it started working. Thanks for your help.

**Comment by texel** [comment]
Haha no problem. I should make it output some information if you run it without any parameters, what happens now is certainly not expected behavior.
